### PR TITLE
Added support for Bootstrap 4

### PR DESCRIPTION
**Pull request by romaricdrigon**
Hello,

This is an updated version of #206, since I need that:

 - [x] branch was rebased
 - [x] README was updated
 - [x] some tests were added
 - [x] `rel` attributes are handled

I hope we can get that merged in soon, thank you!

### CODE REVIEW

**Comment by romaricdrigon** [comment]
Tests were copied but not correct, I'm working on that right now.

**Comment by romaricdrigon** [comment]
Tests were fixed, everything's green @sampart!

**Comment by sampart** [comment]
Thanks for putting this together, @romaricdrigon; I know that lots of people have been hoping for this one.

**Comment by sampart** [comment]
I've added a new release to include this: https://github.com/whiteoctober/Pagerfanta/releases/tag/v1.0.5

**Comment by romaricdrigon** [comment]
Great, thank you for your reactivity @sampart 🍺

**Pull request merged**
