### PR TITLE
Add support for Bootstrap 4

### PR DESCRIPTION
**Pull request by hubgit**
https://v4-alpha.getbootstrap.com/components/pagination/
- Adds `page-item` class to `li` elements
- Adds `page-link` class to `a` and `span` elements
- Adds `twitter_bootstrap4` view

### CODE REVIEW

**Comment by romaricdrigon** [comment]
Any chance this get some attention?
If the only blocking thing is the rebase, I can open a PR from my own repo.

**Comment by sampart** [comment]
Hi @hubgit, thanks for contributing!  There are a few things I need from you before I can merge this PR; please could you do the following?

- rebase your branch off master so that it doesn't have merge conflicts
- update the [Views](https://github.com/whiteoctober/Pagerfanta#views) section of the README to mention the new view
- add some tests - you can probably copy and adapt `TwitterBootstrap3ViewTest.php`
- add `rel="prev"` and `rel="next"` appropriately to keep this inline with the other views - see #209 for how those attributes were added into the other existing views

Thanks again,
Sam

**Comment by sampart** [comment]
PS Sorry for my delay in replying!

**Comment by bogdaniel** [comment]
... can't wait for this commit to go into master =D

**Comment by hubgit** [comment]
I'm not using this at the moment, so hopefully someone else can finish off the PR to make it ready for merging.

**Comment by sampart** [comment]
(This might help if someone does pick it up: http://stackoverflow.com/questions/5884784/how-to-pull-remote-branch-from-somebody-elses-repo)

**Comment by sampart** [comment]
This functionality is now in https://github.com/whiteoctober/Pagerfanta/pull/226.

**Pull request closed without merging**
