### PR TITLE
Implement a combined adapter

### PR DESCRIPTION
**Pull request by mikemeier**
We needed a pagination over multiple sources. This adapter should solve this use case.

### CODE REVIEW

**Comment by stof** [comment]
what is the difference between that adapter and the existing ConcatenationAdapter which already solves that use case AFAIK ?

**Comment by mikemeier** [comment]
Hmm, sorry for that. My current used version of pagerfanta did not have such an adapter. Maybe we could replace the code with the one I provided, since I think it's more readable and using yield instead of adding a new array to memory. But it can also be closed if its not worth the effort :-)

**Comment by stof** [comment]
I don't think it is worth the effort, especially given that maintainers are not really active anymore.

Btw, I see now reason why your adapter has a `getAdapters` method exposing its internal details.

**Comment by mikemeier** [comment]
I also did not see why ArrayAdapter has a getArray method, I just tried to be as close as possible to the other adapters

**Pull request closed without merging**
