### PR TITLE
PSR-4 return type fix

### PR DESCRIPTION
**Pull request by demenkov**
Sorry, i fixed only my case in previous pull.
Added fix for `@return Boolean`
https://github.com/whiteoctober/Pagerfanta/issues/266

### CODE REVIEW

**Comment by sampart** [comment]
Thanks, @demenkov!  Let me know if you need a release creating for this.

**Comment by demenkov** [comment]
Yes, I think @omgmashina would be glad

**Comment by sampart** [comment]
No problem.  Done: https://github.com/whiteoctober/Pagerfanta/releases/tag/v2.1.1

**Comment by omgmashina** [comment]
Could you please update packagist page as well?

**Comment by sampart** [comment]
Ah yes, sorry.  I forgot that Packagist auto-update wasn't working.  I've manually triggered an update now.  Thanks

**Pull request merged**
