### PR TITLE
Let exception interface extend throwable

### PR DESCRIPTION
**Pull request by BackEndTea**

### CODE REVIEW

**Comment by sampart** [comment]
Good thinking, @BackEndTea.  However, http://php.net/manual/en/class.throwable.php says:
> PHP classes cannot implement the Throwable interface directly, and must instead extend Exception.

Do you therefore need to change this to extend `\Exception`?

**Comment by BackEndTea** [comment]
If the exception interface was a class then yes, but interfaces are allowed to extend `\Throwable`. It just means that this interface can only be implemented by classes extending `\Exception`, which is the intention anyways.

**Comment by sampart** [comment]
Ah, perfect.  Thanks for clarifying, and for contributing.  I've merged this now.  Do you need a release making?

**Comment by BackEndTea** [comment]
Thanks for the merge; I don't need a direct release, i just noticed it while looking at the code.

**Pull request merged**
