### PR TITLE
Adds notice to DbalAdapter about GROUP BY usage

### PR DESCRIPTION
**Pull request by sagikazarmark**

### CODE REVIEW

**Comment by stof** [comment]
This notice is very misleading. If you use groupBy, it means you need a much more complex way to count the results. It is not only a matter of resetting the groupBy part. It depends of many other things

**Comment by sagikazarmark** [comment]
I am open to suggestions. Honestly, I didn't think of any other use cases.

**Comment by stof** [comment]
the issue is that if you have both GROUP BY and HAVING in your query, you cannot drop the GROUP BY clause in your count query, because the number of results is impacted by the grouping.

**Comment by sagikazarmark** [comment]
Hmmm, true.

**Comment by pablodip** [comment]
Closing then. It may be interesting linking a webpage where sql counting is explained.

**Pull request closed without merging**
